version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-trusted-children"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14n03t9zqny4u"
s3_prefix = "sam-trusted-children"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
