AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Trysted Children V2

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100

Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/helloWorld.helloWorld
      Description: A simple Hello World example
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  getByRecipientIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getByRecipientId.getByRecipientIdHandler
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{recipientID}
            Method: GET

  putSingleItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putSingleItem.putSingleItemHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            # Auth:
            #   ApiKeyRequired: true

  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: recipientID
          AttributeType: S
        - AttributeName: senderID
          AttributeType: S
      KeySchema:
        - AttributeName: recipientID
          KeyType: HASH
        - AttributeName: senderID
          KeyType: RANGE
