AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Trysted Children V2

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        HASHED_API_KEY: "c8b51b731a62386fd89d9598fb3508c2ff396b91282a888fad66bc615a4771ba"

Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/helloWorld.helloWorld
      Description: A simple Hello World example
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  
  HelloWorldFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref helloWorldFunction]]
      RetentionInDays: 30

  getByRecipientIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getByRecipientId.getByRecipientIdHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{recipientID}
            Method: GET

  GetByRecipientIdFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref getByRecipientIdFunction]]
      RetentionInDays: 30

  putItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putItems.putItemsHandler
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            # Auth:
            #   ApiKeyRequired: true
  
  putItemsFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref putItemsFunction]]
      RetentionInDays: 30

  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: recipientID
          AttributeType: S
        - AttributeName: senderID
          AttributeType: S
      KeySchema:
        - AttributeName: recipientID
          KeyType: HASH
        - AttributeName: senderID
          KeyType: RANGE
