AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Trusted Children 0.2

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        HASHED_API_KEY: "c8b51b731a62386fd89d9598fb3508c2ff396b91282a888fad66bc615a4771ba"
        PUBLIC_KEY_UUID_MAPPING: !Ref UuidAndPublicKeyMap
        LAST_KNOWN_POSITIONS_TABLE: !Ref LastKnownPositionsTable

Resources:
  putPublicKeyAndUuidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putPublicKeyAndUuid.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UuidAndPublicKeyMap          
      Events:
        Api:
          Type: Api
          Properties:
            Path: /devices
            Method: PUT

  getPublicKeyFromUuidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getPublicKeyFromUuid.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UuidAndPublicKeyMap          
      Events:
        Api:
          Type: Api
          Properties:
            Path: /devices/{uuid}
            Method: GET

  putLastKnownPosition:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putLastKnownPosition.handler
      Policies:        
        - DynamoDBCrudPolicy:
            TableName: !Ref LastKnownPositionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: PUT            

  getLastKnownPositionFromRecipientId:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getLastKnownPositionFromRecipientId.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LastKnownPositionsTable      
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{recipientID}
            Method: GET
  
  LastKnownPositionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: recipientId
          AttributeType: S
        - AttributeName: senderId
          AttributeType: S
      KeySchema:
        - AttributeName: recipientId
          KeyType: HASH
        - AttributeName: senderId
          KeyType: RANGE

  UuidAndPublicKeyMap:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
