AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Trysted Children V2

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        HASHED_API_KEY: "c8b51b731a62386fd89d9598fb3508c2ff396b91282a888fad66bc615a4771ba"
        PUBLIC_KEY_AND_UUID_MAPPING_TABLE: !Ref PublicKeyAndUuidMappingTable
        LAST_KNOWN_POSITIONS_TABLE: !Ref LastKnownPositionsTable

Resources:
  ClaimPublicKeyAndUuidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/claimPublicKeyAndUuid.claimPublicKeyAndUuidHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PublicKeyAndUuidMappingTable          
      Events:
        Api:
          Type: Api
          Properties:
            Path: /devices/
            Method: POST

  ClaimPublicKeyAndUuidFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref ClaimPublicKeyAndUuidFunction]]
      RetentionInDays: 30

  GetPublicKeyOnFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getPublicKeyOnFile.getPublicKeyOnFileHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PublicKeyAndUuidMappingTable          
      Events:
        Api:
          Type: Api
          Properties:
            Path: /devices/{uuid}
            Method: GET

  GetPublicKeyOnFileFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetPublicKeyOnFileFunction]]
      RetentionInDays: 30


  GetByRecipientIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getByRecipientId.getByRecipientIdHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LastKnownPositionsTable      
      Events:
        Api:
          Type: Api
          Properties:
            Path: /positions/{recipientID}
            Method: GET

  GetByRecipientIdFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetByRecipientIdFunction]]
      RetentionInDays: 30

  PutItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putItems.putItemsHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LastKnownPositionsTable          
      Events:
        Api:
          Type: Api
          Properties:
            Path: /positions
            Method: POST
  
  PutItemsFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PutItemsFunction]]
      RetentionInDays: 30

  LastKnownPositionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: recipientID
          AttributeType: S
        - AttributeName: senderID
          AttributeType: S
      KeySchema:
        - AttributeName: recipientID
          KeyType: HASH
        - AttributeName: senderID
          KeyType: RANGE
  
  PublicKeyAndUuidMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
