on:
  push:
    branches:
      - master
jobs:
  sonarcloud:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
  
  unit-test:
    runs-on: ubuntu-latest
    needs: sonarcloud
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v2      
      - run: yarn
      - run: yarn test -- __tests__/unit/
        
  build-deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v2      
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1      
      - run: sam build --use-container

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket sam-github-deployment --capabilities CAPABILITY_IAM --region eu-west-1

  post-release-tests:
      runs-on: ubuntu-latest
      needs: build-deploy
      defaults:
        run:
          working-directory: ./Backend
      steps:
        - uses: actions/checkout@v2      
        - run: echo "{\"API_KEY\":\"${{ secrets.API_KEY }}\"}" > __tests__/live/config.json
        - run: yarn
        - run: yarn test -- __tests__/live/
