on:
  push:
    branches:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - run: pwd
      - run: ls
      - run: cd Backend && yarn
      - run: cd Backend && yarn test -- __tests__/unit/
        
  build-deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2      
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      # sam build       
      - run: pwd
      - run: ls
      - run: sam build --use-container -t Backend/template.yaml

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket sam-github-deployment --capabilities CAPABILITY_IAM --region eu-west-1

  post-release-tests:
      runs-on: ubuntu-latest
      needs: build-deploy
      steps:
        - run: cd Backen && yarn
        - run: cd Backend && yarn test -- __tests__/live/
